Numpy

In [1]:
2+2

4

#NUMPY

In [2]:
arr=[12,9,6,6]

In [3]:
import numpy as np

In [4]:
arr=[2,2,2,3]

In [5]:
my_arr=np.array(arr)

In [6]:
print(my_arr)

[2 2 2 3]


In [7]:
my_arr

array([2, 2, 2, 3])

In [8]:
my_list=[[1,2,3],[2,4,5],[4,56,6]]

In [9]:
value=np.array(my_list)

In [10]:
value

array([[ 1,  2,  3],
       [ 2,  4,  5],
       [ 4, 56,  6]])

In [11]:
ankit=np.arange(0,11)

In [12]:
ankit

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
ankit=np.arange(0,11,2)

In [14]:
ankit=np.arange(0,11,2)

In [15]:
ankit

array([ 0,  2,  4,  6,  8, 10])

In [16]:
arr=np.zeros(4)

In [17]:
arr

array([0., 0., 0., 0.])

In [18]:
arr=np.zeros((3,3))

In [19]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
arr=np.ones(3)

In [21]:
arr


array([1., 1., 1.])

In [22]:
arr=np.ones((4,4))

In [23]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
type(arr)

numpy.ndarray

In [25]:
np.ndim(arr)

2

In [26]:
np.ndim(arr)

2

In [27]:
arr=np.array([1,2,3])

In [28]:
arr

array([1, 2, 3])

In [29]:
arr.dtype

dtype('int64')

In [30]:
np.array([3,4,3],dtype="float64")

array([3., 4., 3.])

In [31]:
import numpy as np

np.array(73)

In [32]:
a=np.array(83)

In [33]:
a

array(83)

In [34]:
a.ndim


0

In [35]:
a.dtype

dtype('int64')

In [36]:
np.linspace(3,8,3)

array([3. , 5.5, 8. ])

In [37]:
np.linspace(0,1,37)

array([0.        , 0.02777778, 0.05555556, 0.08333333, 0.11111111,
       0.13888889, 0.16666667, 0.19444444, 0.22222222, 0.25      ,
       0.27777778, 0.30555556, 0.33333333, 0.36111111, 0.38888889,
       0.41666667, 0.44444444, 0.47222222, 0.5       , 0.52777778,
       0.55555556, 0.58333333, 0.61111111, 0.63888889, 0.66666667,
       0.69444444, 0.72222222, 0.75      , 0.77777778, 0.80555556,
       0.83333333, 0.86111111, 0.88888889, 0.91666667, 0.94444444,
       0.97222222, 1.        ])

In [38]:
arr,spacing=np.linspace(8,9,38,retstep=True)

In [39]:
spacing


0.02702702702702703

In [40]:
arr=np.linspace(3,4)

In [41]:
arr

array([3.        , 3.02040816, 3.04081633, 3.06122449, 3.08163265,
       3.10204082, 3.12244898, 3.14285714, 3.16326531, 3.18367347,
       3.20408163, 3.2244898 , 3.24489796, 3.26530612, 3.28571429,
       3.30612245, 3.32653061, 3.34693878, 3.36734694, 3.3877551 ,
       3.40816327, 3.42857143, 3.44897959, 3.46938776, 3.48979592,
       3.51020408, 3.53061224, 3.55102041, 3.57142857, 3.59183673,
       3.6122449 , 3.63265306, 3.65306122, 3.67346939, 3.69387755,
       3.71428571, 3.73469388, 3.75510204, 3.7755102 , 3.79591837,
       3.81632653, 3.83673469, 3.85714286, 3.87755102, 3.89795918,
       3.91836735, 3.93877551, 3.95918367, 3.97959184, 4.        ])

In [42]:
arr.shape

(50,)

In [43]:
np.eye(45)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [44]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [45]:
np.eye(4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [46]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [47]:
np.random.rand(3)

array([0.0700701 , 0.37541383, 0.29515782])

In [48]:
np.random.rand(3,4)

array([[0.88972023, 0.4922778 , 0.61210113, 0.63301526],
       [0.59356008, 0.54162367, 0.1803439 , 0.12388123],
       [0.75619453, 0.2885195 , 0.00390705, 0.08719104]])

In [49]:
np.random.randn(3)

array([ 0.00418545, -0.03059538, -0.43724999])

In [50]:
np.random.randn(3,4)

array([[ 0.93304421,  1.07159166, -0.02848562,  0.89040798],
       [ 0.95337778,  0.64738471, -0.84097477,  0.73285566],
       [-0.75880109, -0.49330713,  1.2953714 , -0.47906825]])

In [51]:
np.random.randint(0,82)

44

In [52]:
np.random.randint(0,28,28)

array([18,  5, 21,  0, 22,  2, 12, 27,  3, 20, 11, 15, 17,  6, 11,  5,  6,
        6, 24, 11,  4,  5,  2,  0,  7, 20, 19, 15])

In [53]:
np.random.randint(3,83,(3,2))

array([[79, 18],
       [38, 24],
       [52, 49]])

In [54]:
np.random.seed(63)
np.random.randint(3,8,3)

array([7, 7, 6])

In [55]:
arr=np.arange(83)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82])

In [57]:
rnd_arr=np.random.randint(0,38,83)

In [58]:
rnd_arr

array([23, 18, 32, 17,  0, 14, 27,  6, 19, 14, 37, 26, 24, 21, 32, 25,  7,
       37, 14, 10,  6,  4, 13, 30,  5, 15, 34,  1, 18, 20, 35, 16,  0,  9,
       22, 10, 21, 10, 26,  1,  6,  4, 19, 16, 32, 34,  0, 25, 29,  8, 13,
       25, 29,  3, 24, 16, 16, 32, 13,  6, 37,  7, 35, 22, 29,  8, 12,  6,
       33, 36,  9, 32, 37, 23, 30,  1, 34, 20, 10, 36, 34, 34,  1])

In [59]:
np.arange(38).reshape(19,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37]])

In [60]:
rnd_arr.max

<function ndarray.max>

In [61]:
rnd.max()

NameError: name 'rnd' is not defined

In [62]:
rnd_arr.max()

37

In [63]:
rnd_arr.argmax()

10

In [64]:
rnd_arr.min()

0

In [65]:
rnd_arr.argmin()

4

In [66]:
np.random.randint(0,38,34).reshape(17,2)

array([[18, 37],
       [31, 23],
       [ 3, 12],
       [36,  9],
       [16, 20],
       [21, 34],
       [ 4, 11],
       [ 9, 28],
       [20, 36],
       [ 6, 30],
       [27, 34],
       [20,  2],
       [11, 31],
       [35, 31],
       [14, 28],
       [ 9,  5],
       [34, 27]])

In [67]:
arr=np.arange(34)

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [69]:
arr[0]

0

In [70]:
arr[3]

3

In [71]:
arr[0:3]

array([0, 1, 2])

In [72]:
arr[:3]

array([0, 1, 2])

In [73]:
arr[3:4]

array([3])

In [74]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [75]:
arr[3:8:2]

array([3, 5, 7])

In [76]:
arr_slice=arr[3:9:4]

In [77]:
arr_slice

array([3, 7])

In [78]:
arr_slice[:]

array([3, 7])

In [79]:
arr_slice[:]=0

In [80]:
arr_slice

array([0, 0])

In [81]:
arr[0:3]=0

In [82]:
arr


array([ 0,  0,  0,  0,  4,  5,  6,  0,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [83]:
arr[:]=100

In [84]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100])

In [85]:
mat=np.arange(0,35).reshape(7,5)

In [86]:
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [87]:
mat[4,4]

24

In [88]:
mat[3,4]

19

In [89]:
mat[:,3]

array([ 3,  8, 13, 18, 23, 28, 33])

In [90]:
mat[:2,:2]

array([[0, 1],
       [5, 6]])

In [84]:
mat[3:,3:]

array([[18, 19],
       [23, 24],
       [28, 29],
       [33, 34]])

In [85]:
mat[::3,3
   ]

array([ 3, 18, 33])

In [94]:
mat=np.zeros((10,10))


In [95]:
mat


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

for i in range(mat.shape[2]):

In [96]:
for i in range(mat.shape[1]):
    mat[i]=i

In [97]:
mat

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [98]:
mat[[2,2,3,4]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [99]:
arr=np.arange(0,8)

In [100]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [101]:
arr> 3

array([False, False, False, False,  True,  True,  True,  True])

In [103]:
filter =arr>3

In [105]:
arr[filter]

array([4, 5, 6, 7])

In [106]:
arr[arr<3]

array([0, 1, 2])

In [107]:
np.arange(3,8)

array([3, 4, 5, 6, 7])

In [108]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [109]:
arr**6

array([     0,      1,     64,    729,   4096,  15625,  46656, 117649])

In [110]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0])

In [111]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [112]:
arr/arr

/home/ankittt2001/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [113]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [114]:
1/arr

/home/ankittt2001/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714])

In [115]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [116]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [117]:
np.min(arr)

0

In [118]:
np.log(arr)

/home/ankittt2001/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015])

In [119]:
np.max(arr)

7

In [121]:
mat1=np.array(([3,3,4],[4,5,3]))

In [122]:
mat2=np.array(([3,4,3],[5,6,7]))

In [123]:
mat1+mat2

array([[ 6,  7,  7],
       [ 9, 11, 10]])

In [126]:
np.add(mat1,mat2)

array([[ 6,  7,  7],
       [ 9, 11, 10]])

In [127]:
np.divide(mat1,mat2)

array([[1.        , 0.75      , 1.33333333],
       [0.8       , 0.83333333, 0.42857143]])

In [128]:
np.multiply(mat2,mat1)

array([[ 9, 12, 12],
       [20, 30, 21]])

In [129]:
np.subtract(mat1,mat2)

array([[ 0, -1,  1],
       [-1, -1, -4]])

In [130]:
np.sum(mat1)

22

In [132]:
np.sum(mat1,axis=1)

array([10, 12])

In [133]:
v=np.array([3,5])
w=np.array([3,8])

In [134]:
v.dot(w)

49

In [135]:
np.dot(v,w)

49

In [136]:
mat1.T

array([[3, 4],
       [3, 5],
       [4, 3]])

In [146]:
arr=np.arange(0,9).reshape(3,3)


In [147]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [148]:
arr+np.array([1,1,1])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])